### ISSUE TITLE
Value 0 is not shown in RangeSlider

### ISSUE THREAD

**Issue by jonnitto** [mireo91/RepeatableFields#14]
If it is possible to set a value to 0, the number 0 is not shown in the input field.

https://github.com/mireo91/RepeatableFields/assets/4510166/67a29ac7-877d-4959-a28e-b3e5531f0781

```yaml
              verticalAlignment:
                label: Vertical alignment
                editor: 'Neos.Neos/Inspector/Editors/RangeEditor'
                defaultValue: 0
                editorOptions:
                  min: -90
                  max: 90
                  step: 1
                  unit: '%'
```

If I set the type to `integer`, the range slider didn't get rendered and I get a input field. The `editor` setting should override the default editor anyway
