### ISSUE TITLE
How to get assets

### ISSUE THREAD

**Issue by jonnitto** [mireo91/RepeatableFields#2]
Hey, very cool plugin! Thank you for creating this!

If I have a nested property `image` like this

```yaml
  gallery:
      type: repeatable
      ui:
        label: Gallery
        inspector:
          group: gallery
          editorOptions:
            buttonAddLabel: Add image
            properties:
              image:
                type: Neos\Media\Domain\Model\ImageInterface
                label: Image
```

How can get the specific asset? 
This won't work:
```
gallery = Neos.Fusion:Map {
      items = ${q(node).property('gallery')}
      itemRenderer = Neos.Neos:ImageUri {
          asset = ${item.image}
          maximumWidth = 1200
      }
 }
```
