### ISSUE TITLE
If an editor is set for one subproperty, it get's applied to all

### ISSUE THREAD

**Issue by jonnitto** [mireo91/RepeatableFields#6]
If I have the following setting:

```yaml
contactPersons:
    type: repeatable
    ui:
      inspector:
        editorOptions:
          properties:
            name:
              label: Name
              type: string
            phone:
              label: Telefon
              type: string
              editor: 'Neos.Neos/Inspector/Editors/TextAreaEditor'
```

The name also gets a textarea field. The same happens if I add a validation, it gets applied to all
