### ISSUE TITLE
editor option doesn't work if type is string

### ISSUE THREAD

**Issue by jonnitto** [mireo91/RepeatableFields#9]
If I have got a property set like this:

```yaml
buttons:
  type: repeatable
  ui:
    label: 'Buttons'
    inspector:
      editorOptions:
        buttonAddLabel: 'Add Link'
        properties:
          text:
            type: string
            label: 'Text'
          link:
            type: string
            label: Link
            editor: 'Neos.Neos/Inspector/Editors/LinkEditor'
```

The editor doesn't get loaded, it is a normal text field:
<img width="450" alt="Xnapper-2023-03-16-16 50 33" src="https://user-images.githubusercontent.com/4510166/225675545-46311b6a-4154-48ff-ad8a-3e949e7dd8bc.png">
